[build]
  functions = "netlify/functions"

[[redirects]]
  # Redirect for paths starting with /product/01/... and pass all query parameters to the serverless function
  from = "/product/01/*"
  to = "/.netlify/functions/resolve"
  status = 200
  query = {path = ":splat"}

[[redirects]]
  # Catch-all redirect for SPA client-side routing, allowing query parameters to pass to the front end
  from = "/*"
  to = "/index.html"
  status = 200
